package issues

const (
	DomainTechnical      = "technical"
	DomainOnPage         = "onpage"
	DomainContent        = "content"
	DomainAccessibility  = "accessibility"
	DomainStructuredData = "structured_data"
	DomainLocal          = "local"
	DomainInternational  = "international"
	DomainLinks          = "links"
)

const (
	CodeHTTPClientError          = "http.4xx"
	CodeHTTPServerError          = "http.5xx"
	CodeRedirect                 = "http.redirect"
	CodeMissingTitle             = "meta.title.missing"
	CodeDuplicateTitle           = "meta.title.duplicate"
	CodeTitleTooShort            = "meta.title.short"
	CodeTitleTooLong             = "meta.title.long"
	CodeMissingMetaDescription   = "meta.description.missing"
	CodeMetaDescriptionOgOnly    = "meta.description.og_only"
	CodeDuplicateMetaDescription = "meta.description.duplicate"
	CodeMetaDescriptionTooShort  = "meta.description.short"
	CodeMetaDescriptionTooLong   = "meta.description.long"
	CodeTitleH1Duplicate         = "meta.title.h1_duplicate"
	CodeTitleDescDuplicate       = "meta.title.desc_duplicate"
	CodeMissingH1                = "heading.h1.missing"
	CodeMultipleH1               = "heading.h1.multiple"
	CodeMissingH2                = "heading.h2.missing"
	CodeMissingCanonical         = "canonical.missing"
	CodeCanonicalOffOrigin       = "canonical.off_origin"
	CodeCanonicalSelfMismatch    = "canonical.self_mismatch"
	CodeCanonicalNoindexMismatch = "canonical.noindex_mismatch"
	CodeNoindex                  = "robots.noindex"
	CodeRobotsNofollow           = "robots.nofollow"
	CodeRobotsMetaConflict       = "robots.conflict"
	CodeThinContent              = "content.thin"
	CodeContentNoImages           = "content.no_images"
	CodeSpellHeuristic           = "content.spell_heuristic"
	CodeMissingOgTitle           = "social.og_title.missing"
	CodeMissingOgImage           = "social.og_image.missing"
	CodeMissingTwitterCard       = "social.twitter_card.missing"
	CodeMissingJsonLd            = "schema.jsonld.missing"
	CodeInvalidJsonLd            = "schema.jsonld.invalid"
	CodeWeakJsonLd                = "schema.jsonld.weak"
	CodeImagesMissingAlt         = "a11y.img.alt_missing"
	CodeImagesAllMissingAlt      = "a11y.img.all_alt_missing"
	CodeMissingHTMLLang          = "a11y.html.lang_missing"
	CodeButtonsWithoutName       = "a11y.button.name_missing"
	CodeMissingSkipLink          = "a11y.skip.missing"
	CodeLinksWithoutAccessibleName = "a11y.link.name_missing"
	CodeLocalNapIncomplete       = "local.nap.incomplete"
	CodeMissingViewport          = "mobile.viewport.missing"
	CodeExactDuplicate           = "content.exact_duplicate"
	CodeOrphanPage               = "links.orphan"
	CodeDeepPage                 = "links.deep"
	CodeMissingHreflang          = "intl.hreflang.missing"
	CodeHreflangNotReciprocal    = "intl.hreflang.not_reciprocal"
	CodeSoft404                  = "http.soft_404"
	CodeWeakCitability           = "content.citability.weak"
	CodeOutboundBroken           = "links.outbound.broken"
)
