/**
 * Полная карта SEO-модулей OpenSpider — SF parity + roadmap.
 * status: ready = работает; partial = часть логики есть; planned = каркас.
 */
export const ModuleStatus = {
  Ready: 'ready',
  Partial: 'partial',
  Planned: 'planned',
} as const;

export type ModuleStatusName = (typeof ModuleStatus)[keyof typeof ModuleStatus];

export const SeoDomain = {
  Technical: 'technical',
  OnPage: 'on_page',
  Content: 'content',
  Links: 'links',
  StructuredData: 'structured_data',
  International: 'international',
  Performance: 'performance',
  Accessibility: 'accessibility',
  SearchMetrics: 'search_metrics',
  Behaviour: 'behaviour',
  Rankings: 'rankings',
  OffPage: 'off_page',
  Local: 'local',
  Competitive: 'competitive',
  Reporting: 'reporting',
  Automation: 'automation',
  LabsTools: 'labs_tools',
} as const;

export type SeoDomainName = (typeof SeoDomain)[keyof typeof SeoDomain];

export interface SeoModule {
  id: string;
  domain: SeoDomainName;
  name: string;
  description: string;
  status: ModuleStatusName;
  lifts: string[];
}

export const SEO_MODULES: SeoModule[] = [
  {
    id: 'spider',
    domain: SeoDomain.Technical,
    name: 'Site Spider',
    description: 'Unlimited HTTP crawl, queue, robots.txt, live URL table.',
    status: ModuleStatus.Ready,
    lifts: ['Indexation', 'Crawl budget'],
  },
  {
    id: 'crawl-config',
    domain: SeoDomain.Technical,
    name: 'Crawl configuration',
    description: 'Concurrency, depth, UA, robots, sitemap seed, JS render toggle.',
    status: ModuleStatus.Ready,
    lifts: ['Crawl control'],
  },
  {
    id: 'indexability',
    domain: SeoDomain.Technical,
    name: 'Indexability',
    description: 'noindex, robots meta, canonical conflicts.',
    status: ModuleStatus.Ready,
    lifts: ['Index coverage'],
  },
  {
    id: 'redirects',
    domain: SeoDomain.Technical,
    name: 'Redirects & status',
    description: '4xx/5xx, redirect targets.',
    status: ModuleStatus.Ready,
    lifts: ['Crawl health'],
  },
  {
    id: 'sitemaps',
    domain: SeoDomain.Technical,
    name: 'XML Sitemaps',
    description: 'Generate sitemap from crawl; seed from robots sitemaps.',
    status: ModuleStatus.Ready,
    lifts: ['Discovery'],
  },
  {
    id: 'js-render',
    domain: SeoDomain.Technical,
    name: 'JavaScript rendering',
    description: 'Electron/Chromium render for SPA/CSR HTML.',
    status: ModuleStatus.Ready,
    lifts: ['JS SEO'],
  },
  {
    id: 'mobile',
    domain: SeoDomain.Technical,
    name: 'Mobile friendliness',
    description: 'Viewport meta and basic mobile signals from HTML.',
    status: ModuleStatus.Ready,
    lifts: ['Mobile UX'],
  },
  {
    id: 'site-viz',
    domain: SeoDomain.Technical,
    name: 'Site visualization',
    description: 'Internal link graph from crawl.',
    status: ModuleStatus.Ready,
    lifts: ['Architecture'],
  },
  {
    id: 'titles-meta',
    domain: SeoDomain.OnPage,
    name: 'Titles & meta',
    description: 'Missing/duplicate/length title & description checks.',
    status: ModuleStatus.Ready,
    lifts: ['CTR', 'Relevance'],
  },
  {
    id: 'headings',
    domain: SeoDomain.OnPage,
    name: 'Headings',
    description: 'H1 presence/count and H2 on content-rich pages.',
    status: ModuleStatus.Ready,
    lifts: ['On-page structure'],
  },
  {
    id: 'serp-preview',
    domain: SeoDomain.OnPage,
    name: 'SERP preview',
    description: 'Pixel-ish title/description preview for snippets.',
    status: ModuleStatus.Ready,
    lifts: ['CTR'],
  },
  {
    id: 'social-tags',
    domain: SeoDomain.OnPage,
    name: 'Open Graph / Twitter',
    description: 'Detect missing OG/Twitter tags.',
    status: ModuleStatus.Ready,
    lifts: ['Social CTR'],
  },
  {
    id: 'thin-content',
    domain: SeoDomain.Content,
    name: 'Thin content',
    description: 'Word-count thresholds.',
    status: ModuleStatus.Ready,
    lifts: ['Engagement'],
  },
  {
    id: 'exact-dup',
    domain: SeoDomain.Content,
    name: 'Exact duplicates',
    description: 'Identical content hash across URLs.',
    status: ModuleStatus.Ready,
    lifts: ['Index quality'],
  },
  {
    id: 'near-dup',
    domain: SeoDomain.Content,
    name: 'Near-duplicates',
    description: 'Similarity across URLs.',
    status: ModuleStatus.Ready,
    lifts: ['Index quality'],
  },
  {
    id: 'spellcheck',
    domain: SeoDomain.Content,
    name: 'Spell & grammar',
    description: 'Content polish heuristics (repeats, ALL-CAPS, punctuation).',
    status: ModuleStatus.Ready,
    lifts: ['Content quality'],
  },
  {
    id: 'internal-links',
    domain: SeoDomain.Links,
    name: 'Internal links',
    description: 'In/out counts, orphans, deep pages, graph viz.',
    status: ModuleStatus.Ready,
    lifts: ['PageRank flow'],
  },
  {
    id: 'broken-links',
    domain: SeoDomain.Links,
    name: 'Broken links',
    description: '4xx/5xx from discovery.',
    status: ModuleStatus.Ready,
    lifts: ['UX', 'Crawl health'],
  },
  {
    id: 'structured-data',
    domain: SeoDomain.StructuredData,
    name: 'Structured data',
    description: 'JSON-LD detect, type parse, weak/invalid issues.',
    status: ModuleStatus.Ready,
    lifts: ['Rich results'],
  },
  {
    id: 'hreflang',
    domain: SeoDomain.International,
    name: 'Hreflang',
    description: 'Collect hreflang and verify reciprocal pairs.',
    status: ModuleStatus.Ready,
    lifts: ['Intl targeting'],
  },
  {
    id: 'psi-cwv',
    domain: SeoDomain.Performance,
    name: 'PageSpeed / CWV',
    description: 'PSI / Lighthouse scores and CWV lab metrics.',
    status: ModuleStatus.Ready,
    lifts: ['Core Web Vitals'],
  },
  {
    id: 'a11y',
    domain: SeoDomain.Accessibility,
    name: 'Accessibility audit',
    description: 'img alt, html lang, skip link, unnamed links/buttons.',
    status: ModuleStatus.Ready,
    lifts: ['UX', 'A11y'],
  },
  {
    id: 'custom-search',
    domain: SeoDomain.LabsTools,
    name: 'Custom source search',
    description: 'Regex search across stored HTML from crawl.',
    status: ModuleStatus.Ready,
    lifts: ['Forensics'],
  },
  {
    id: 'custom-extract',
    domain: SeoDomain.LabsTools,
    name: 'Custom extraction',
    description: 'CSS selector extract into result rows.',
    status: ModuleStatus.Ready,
    lifts: ['Scraping'],
  },
  {
    id: 'custom-js',
    domain: SeoDomain.LabsTools,
    name: 'Custom JavaScript',
    description: 'User JS against stored HTML with cheerio $ in sandbox.',
    status: ModuleStatus.Ready,
    lifts: ['Automation'],
  },
  {
    id: 'ai-scan',
    domain: SeoDomain.LabsTools,
    name: 'OpenAI / Gemini scan',
    description: 'AI page audits via chat completions (first 5 pages).',
    status: ModuleStatus.Ready,
    lifts: ['Content insights'],
  },
  {
    id: 'gsc',
    domain: SeoDomain.SearchMetrics,
    name: 'Google Search Console',
    description: 'CSV import overlay for clicks, impressions, queries.',
    status: ModuleStatus.Ready,
    lifts: ['Clicks', 'Impressions'],
  },
  {
    id: 'yandex-webmaster',
    domain: SeoDomain.SearchMetrics,
    name: 'Яндекс Вебмастер',
    description: 'CSV import overlay for Webmaster exports.',
    status: ModuleStatus.Ready,
    lifts: ['Yandex visibility'],
  },
  {
    id: 'metrika',
    domain: SeoDomain.Behaviour,
    name: 'Яндекс Метрика',
    description: 'Visits overlay via Metrika API (counter + OAuth token).',
    status: ModuleStatus.Ready,
    lifts: ['Engagement'],
  },
  {
    id: 'ga4',
    domain: SeoDomain.Behaviour,
    name: 'Google Analytics 4',
    description: 'CSV import overlay for sessions on crawled URLs.',
    status: ModuleStatus.Ready,
    lifts: ['Engagement'],
  },
  {
    id: 'rank-tracker',
    domain: SeoDomain.Rankings,
    name: 'Rank tracker',
    description: 'Keyword rank history saved after SERP probes.',
    status: ModuleStatus.Ready,
    lifts: ['Visibility'],
  },
  {
    id: 'backlinks',
    domain: SeoDomain.OffPage,
    name: 'Link metrics / backlinks',
    description: 'CSV import overlay for referring domains and anchors.',
    status: ModuleStatus.Ready,
    lifts: ['Authority'],
  },
  {
    id: 'local-seo',
    domain: SeoDomain.Local,
    name: 'Local SEO',
    description: 'NAP consistency in JSON-LD.',
    status: ModuleStatus.Ready,
    lifts: ['Local pack'],
  },
  {
    id: 'list-mode',
    domain: SeoDomain.Competitive,
    name: 'List / competitor mode',
    description: 'Crawl a pasted URL list without following links.',
    status: ModuleStatus.Ready,
    lifts: ['Competitive intel'],
  },
  {
    id: 'exports',
    domain: SeoDomain.Reporting,
    name: 'Exports & reports',
    description: 'JSON reports, import, compare.',
    status: ModuleStatus.Ready,
    lifts: ['Delivery'],
  },
  {
    id: 'looker',
    domain: SeoDomain.Reporting,
    name: 'Looker Studio export',
    description: 'Auto CSV export of pages and issues to Documents/OpenSpider/csv.',
    status: ModuleStatus.Ready,
    lifts: ['BI'],
  },
  {
    id: 'scheduling',
    domain: SeoDomain.Automation,
    name: 'Scheduling & alerts',
    description: 'Hourly/daily crawls while the app is open.',
    status: ModuleStatus.Ready,
    lifts: ['Ops'],
  },
  {
    id: 'form-auth',
    domain: SeoDomain.Automation,
    name: 'Form-based authentication',
    description: 'Login form fill via Chromium before crawl.',
    status: ModuleStatus.Ready,
    lifts: ['Auth crawl'],
  },
  {
    id: 'segmentation',
    domain: SeoDomain.Automation,
    name: 'Segmentation',
    description: 'URL segment rules (name|regex) on crawl rows.',
    status: ModuleStatus.Ready,
    lifts: ['Analysis'],
  },
];

export const DOMAIN_LABELS: Record<SeoDomainName, string> = {
  [SeoDomain.Technical]: 'Technical',
  [SeoDomain.OnPage]: 'On-page',
  [SeoDomain.Content]: 'Content',
  [SeoDomain.Links]: 'Links',
  [SeoDomain.StructuredData]: 'Structured data',
  [SeoDomain.International]: 'International',
  [SeoDomain.Performance]: 'Performance',
  [SeoDomain.Accessibility]: 'Accessibility',
  [SeoDomain.SearchMetrics]: 'Search metrics',
  [SeoDomain.Behaviour]: 'Behaviour metrics',
  [SeoDomain.Rankings]: 'Rankings',
  [SeoDomain.OffPage]: 'Off-page',
  [SeoDomain.Local]: 'Local',
  [SeoDomain.Competitive]: 'Competitive',
  [SeoDomain.Reporting]: 'Reporting',
  [SeoDomain.Automation]: 'Automation',
  [SeoDomain.LabsTools]: 'Labs tools',
};
